// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHqVQaheanh3xBT951icead_rS25ncewg',
    appId: '1:784417889490:web:fb70ff3dfa89ca760c610b',
    messagingSenderId: '784417889490',
    projectId: 'order-delivery-project',
    authDomain: 'order-delivery-project.firebaseapp.com',
    storageBucket: 'order-delivery-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChv4zxcfbCH1V3Pwyaf2ZDR7UFwNq89uE',
    appId: '1:784417889490:android:73bc0710ee64513e0c610b',
    messagingSenderId: '784417889490',
    projectId: 'order-delivery-project',
    storageBucket: 'order-delivery-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYJhY5okQTpQY7uhgHwgxN1dsTbN-Tsh0',
    appId: '1:784417889490:ios:85228451298dc6a90c610b',
    messagingSenderId: '784417889490',
    projectId: 'order-delivery-project',
    storageBucket: 'order-delivery-project.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYJhY5okQTpQY7uhgHwgxN1dsTbN-Tsh0',
    appId: '1:784417889490:ios:85228451298dc6a90c610b',
    messagingSenderId: '784417889490',
    projectId: 'order-delivery-project',
    storageBucket: 'order-delivery-project.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHqVQaheanh3xBT951icead_rS25ncewg',
    appId: '1:784417889490:web:7cab2404c8ca43eb0c610b',
    messagingSenderId: '784417889490',
    projectId: 'order-delivery-project',
    authDomain: 'order-delivery-project.firebaseapp.com',
    storageBucket: 'order-delivery-project.firebasestorage.app',
  );
}
